# module du helios launcher
name: Launcher Building
on:
  push:
    branches: [ main ]

jobs:
  # create-release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Get version
  #       run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV

  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ env.version }}
  #         release_name: release ${{ env.version }}
  #         draft: false
  #         prerelease: ${{ contains(env.version, 'beta') || contains(env.version, 'alpha') }}

  build-launcher:
    # needs: create-release
    name: "Build: ${{ matrix.config.name }} / ${{ matrix.config.architecture }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "Ubuntu Latest GCC",
              artifact: "hugin-ubuntu-x64",
              os: ubuntu-22.04,
              cc: "gcc",
              architecture: x64,
            }
          - {
            name: "macOS M1 Latest Clang",
            artifact: "hugin-macos-m1",
            os: macos-12.0,
            cc: "clang",
            architecture: arm64,
          }
          - {
            name: "macOS Latest Clang",
            artifact: "hugin-macos-x64",
            os: macos-12.0,
            cc: "clang",
            architecture: x64,
          }

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run build
        shell: bash